name: Update Config Section(Path)


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - dev
          - stg
          - prd
        default: 'dev'
        required: true
      mapping:
        description: 'Mapping(configMapping|secretsMapping)'
        type: choice
        options:
          - configMapping
          - secretsMapping
        default: 'secretsMapping'
        required: true
      configPath:
        description: 'Config path'
        default: ''
        required: true
      namespaces:
        description: 'Comma separated namespace'
        default: 'app-namespaces'
      scope:
        description: 'Config scope'
        default: 'global'
        type: choice
        options:
          - global
          - auto
        required: true
      key:
        description: 'Config key'
        default: ''
        required: true
      value:
        description: 'Config Value'
        default: ''
        required: true
      dataType:
        description: 'Config datatype'
        default: 'str'
        type: choice
        options:
          - str
          - int
          - float
          - dict
          - list
        required: true
      delete:
        description: 'Delete existing key'
        default: false
        type: boolean


jobs:
  DeployDev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create YAML
      run: |
        python test.py -m ${{ github.event.inputs.mapping }} \
                  -c ${{ github.event.inputs.configPath }} \
                  -n ${{ github.event.inputs.namespaces }} \
                  -k ${{ github.event.inputs.key }} \
                  -s ${{ github.event.inputs.scope }} \
                  -t ${{ github.event.inputs.dataType }} \
                  -v ${{ github.event.inputs.value }} \
                  -o patch.yaml
        echo "Display contents"
        cat patch.yaml

        if [[ ${{ github.event.inputs.delete }} == 'true' ]]; then
            echo "Delete enabled"
        else
            echo "Delete disabled"
        fi

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ github.token }}
        commit-message: Update config
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: config-patches
        delete-branch: true
        title: 'Add/Remove Single config key'
        body: |
          Updated ${{ github.event.inputs.environment }} config
          - Added a single key
        labels: |
          ${{ github.event.inputs.environment }}
          automated pr
        assignees: ${{ github.actor }}
        draft: false
        base: master



